# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: recipeService

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=1.11.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  profile: ${self:custom.profiles.${self:provider.stage}}
  role: arn:aws:iam::480510678140:role/serverless-deploy
  timeout: 15
  environment:
    DYNAMODB_TABLES: RECIPE_TABLES

custom:
  defaultStage: dev
  profiles:
    dev: serverless

  package:
    exclude:
      - node_modules/*

    include:
      - node_modules/async

functions:
  # This function creates new recipes
  createRecipe:
    handler: createRecipe.createRecipe
    events:
      - http:
          path: api/v1/smartchef/createRecipe
          method: post
          cors: true

  # This function fetches all recipes
  getAllRecipes:
    handler: getAllRecipes.getAllRecipes
    events:
      - http:
          path: api/v1/smartchef/getAllRecipes
          method: get
          cors: true

  # This function fetches recipe by id
  getRecipeById:
    handler: getRecipeById.getRecipeById
    events:
      - http:
          path: api/v1/smartchef/getRecipeById/{recipeId}
          method: get
          cors: true

  # This function updates a particular recipe
  updateRecipeById:
    handler: updateRecipeById.updateRecipeById
    events:
      - http:
          path: api/v1/smartchef/updateRecipeById/{recipeId}
          method: put
          cors: true

  # This function deletes a particular recipe
  deleteRecipeById:
    handler: deleteRecipeById.deleteRecipeById
    events:
      - http:
          path: api/v1/smartchef/deleteRecipeById/{recipeId}
          method: delete
          cors: true
